version: '2.0'
services:
  web:
    build:
      context: .  # Path to the directory with Dockerfile
      dockerfile: Dockerfile 
    image: test-loyalty-be
    container_name: test-loyalty-be
    restart: unless-stopped 
    logging:      
      options:
        max-size: "20m"
    networks:
      shared_network:
        ipv4_address: 192.168.1.123
    ports:
      - "3029:3029"
    volumes:
      - ".:/usr/src/app"
      # Don't sync the node_modules directory back to the client.
      - "/usr/src/app/node_modules"
networks:
  shared_network:
    external: true  # Use an existing external network
